### ISSUE TITLE
make it compatible with uxdesign.cc

### ISSUE THREAD

**Issue by 3xploiton3** [GiveMeSomething/unmedium-core#1]
https://bootcamp.uxdesign.cc/5-reasons-to-not-start-a-ux-designer-career-in-2022-2023-5c04d2d527b3

![image](https://github.com/GiveMeSomething/unmedium-core/assets/19517680/ea195ef2-dd59-4b24-bfc9-20b57e066206)

**Comment by GiveMeSomething** [comment]
@3xploiton3 Thank you for using this. I put out a new release to address this issue
