### ISSUE TITLE
[request] javascript.plainenglish.io

### ISSUE THREAD

**Issue by 3xploiton3** [GiveMeSomething/unmedium-core#2]
https://javascript.plainenglish.io/variable-naming-best-practices-for-clean-and-efficient-code-f5eaaad4f591

![image](https://github.com/GiveMeSomething/unmedium-core/assets/19517680/fc293829-a22c-4277-b747-625fa3a563c0)

**Comment by GiveMeSomething** [comment]
I think you are using the `Unmedium` version with reader mode , which only works with websites containing `medium` in theirs hostname. Try using the [core version](https://github.com/GiveMeSomething/unmedium-core)

I haven't found a way to detect whether a website source from Medium or not (they provide custom URL to authors)

@3xploiton3

**Comment by 3xploiton3** [comment]
> I think you are using the `Unmedium` version with reader mode , which only works with websites containing `medium` in theirs hostname. Try using the [core version](https://github.com/GiveMeSomething/unmedium-core)
> 
> I haven't found a way to detect whether a website source from Medium or not (they provide custom URL to authors)
> 
> @3xploiton3

thanks, that worked
